# Seed data for Prague pubs (143 pubs across 13 districts)
# Approximate GPS coordinates for each Prague district
DISTRICT_COORDS = {
    "Praha 1": (50.0875, 14.4213),
    "Prosek": (50.1156, 14.4856),
    "Ládví": (50.1206, 14.4717),
    "Kobylisy": (50.1247, 14.4567),
    "Střížkov": (50.1175, 14.4760),
    "Letňany": (50.1318, 14.5180),
    "Žižkov": (50.0875, 14.4503),
    "Vinohrady": (50.0780, 14.4499),
    "Karlín": (50.0936, 14.4525),
    "Dejvice": (50.1023, 14.3937),
    "Smíchov": (50.0729, 14.4068),
    "Nusle": (50.0640, 14.4396),
    "Holešovice": (50.1031, 14.4395),
    "Břevnov": (50.0830, 14.3580),
}

PUBS = [
    {"id": 1, "nazev": "U Zlatého tygra", "ctvrt": "Praha 1", "pivo": "Pilsner Urquell z tanku"},
    {"id": 2, "nazev": "U Hrocha", "ctvrt": "Praha 1", "pivo": "Pilsner Urquell, Kozel Černý"},
    {"id": 3, "nazev": "Lokál Dlouhááá", "ctvrt": "Praha 1", "pivo": "Pilsner Urquell (Hladinka, Šnyt, Mlíko), Kozel Tmavý"},
    {"id": 4, "nazev": "U Fleků", "ctvrt": "Praha 1", "pivo": "Flekovský tmavý ležák 13° (vlastní)"},
    {"id": 5, "nazev": "U Pinkasů", "ctvrt": "Praha 1", "pivo": "Pilsner Urquell hladinka, Master 13° Tmavý"},
    {"id": 6, "nazev": "Klášterní pivovar Strahov", "ctvrt": "Praha 1", "pivo": "Sv. Norbert Amber Lager, Sv. Norbert Dark, Sv. Norbert IPA"},
    {"id": 7, "nazev": "U Černého vola", "ctvrt": "Praha 1", "pivo": "Kozel 10° Světlý, Kozel Tmavý, Pilsner Urquell"},
    {"id": 8, "nazev": "U Tří růží", "ctvrt": "Praha 1", "pivo": "Světlý speciál 12°, Tmavý ležák, Klášterní speciál 15°"},
    {"id": 9, "nazev": "Pivovarský dům Benedict", "ctvrt": "Praha 1", "pivo": "Štěpán 12° Světlý, Pšeničné pivo, Kávové pivo, Višňové pivo"},
    {"id": 10, "nazev": "U Dvou koček", "ctvrt": "Praha 1", "pivo": "Kočka Světlá 12°, Kočka Tmavá 12°, Pilsner Urquell"},
    {"id": 11, "nazev": "U Medvídků", "ctvrt": "Praha 1", "pivo": "Budvar 12°, X-Beer 33 (nejsilnější pivo), Medvídkovské polotmavé"},
    {"id": 12, "nazev": "Jelínkova Plzeňská pivnice", "ctvrt": "Praha 1", "pivo": "Pilsner Urquell z tanku, Radegast Birell"},
    {"id": 13, "nazev": "U Rudolfina", "ctvrt": "Praha 1", "pivo": "Pilsner Urquell hladinka, Kozel Černý"},
    {"id": 14, "nazev": "Pivnice Štupartská", "ctvrt": "Praha 1", "pivo": "Gambrinus 11° Nepaster, Pilsner Urquell"},
    {"id": 15, "nazev": "The Pub Praha 1", "ctvrt": "Praha 1", "pivo": "Pilsner Urquell (samovýčep na stolech)"},
    {"id": 16, "nazev": "Lokal U Bílé kuželky", "ctvrt": "Praha 1", "pivo": "Pilsner Urquell z tanku, Kozel Tmavý"},
    {"id": 17, "nazev": "Bredovský Dvůr", "ctvrt": "Praha 1", "pivo": "Pilsner Urquell tankový, Kozel Řezaný"},
    {"id": 18, "nazev": "Novoměstský pivovar", "ctvrt": "Praha 1", "pivo": "Novoměstský ležák 11° Světlý, Novoměstský kvasnicový"},
    {"id": 19, "nazev": "Restaurace Mincovna", "ctvrt": "Praha 1", "pivo": "Pilsner Urquell z tanku, Volba sládků"},
    {"id": 20, "nazev": "Pivnice U Poutníka", "ctvrt": "Praha 1", "pivo": "Poutník 12° Hořký, Poutník 14° Speciál"},
    {"id": 21, "nazev": "Pivovar Beznoska", "ctvrt": "Prosek", "pivo": "Beznoska 11° Světlá, Klíčovská 12° Tmavá, Koloušek 13° IPA"},
    {"id": 22, "nazev": "Hospůdka U Knoflíku", "ctvrt": "Prosek", "pivo": "Pilsner Urquell, Kozel 11° Tmavý, Volba sládků"},
    {"id": 23, "nazev": "Restaurace U Branců", "ctvrt": "Prosek", "pivo": "Staropramen 11°, Nealko Stella Artois"},
    {"id": 24, "nazev": "Pivnice Na Vyhlídce", "ctvrt": "Prosek", "pivo": "Svijanský Máz 11°, Bernard 12° Nepasterovaný"},
    {"id": 25, "nazev": "Bar & Pivnice Pod Křížkem", "ctvrt": "Prosek", "pivo": "Gambrinus 11° Nepaster, Kozel 10°"},
    {"id": 26, "nazev": "Pivnice U Šandů", "ctvrt": "Prosek", "pivo": "Radegast Rázná 10, Radegast Ryze Hořká 12"},
    {"id": 27, "nazev": "Letecká hospoda Prosek", "ctvrt": "Prosek", "pivo": "Staropramen 10°, Braník Jedenáctka"},
    {"id": 28, "nazev": "Plzeňka Prosek", "ctvrt": "Prosek", "pivo": "Pilsner Urquell z tanku, Kozel Černý"},
    {"id": 29, "nazev": "Hospoda Na Zdráhalce", "ctvrt": "Prosek", "pivo": "Svijany 11°, Kácov Hubertus"},
    {"id": 30, "nazev": "Pivnice U Pecků", "ctvrt": "Prosek", "pivo": "Gambrinus Excelent 11°, Radegast 12°"},
    {"id": 141, "nazev": "Prosecká Bašta", "ctvrt": "Prosek", "pivo": "Kozel 11°, Pilsner Urquell"},
    {"id": 142, "nazev": "Klub Underground Prosek", "ctvrt": "Prosek", "pivo": "Chotěboř 12°, Únětice 10°"},
    {"id": 31, "nazev": "Pivovar Cobolis", "ctvrt": "Ládví", "pivo": "Cobolis 11° Praotec, Cobolis 12° Nevěsta, IPA 14° El Niňo, Tmavá 13°"},
    {"id": 32, "nazev": "Kozlovna Ládví", "ctvrt": "Ládví", "pivo": "Kozel 11° z tanku, Kozel Černý, Pilsner Urquell"},
    {"id": 33, "nazev": "Hospoda Pod Ládvím", "ctvrt": "Ládví", "pivo": "Gambrinus 11°, Pilsner Urquell, Birell"},
    {"id": 34, "nazev": "Pivnice U Vlka", "ctvrt": "Kobylisy", "pivo": "Svijany 11°, Rohozec Skalák 11°, Primátor Pšeničné"},
    {"id": 35, "nazev": "Restaurace Na Pěšinách", "ctvrt": "Kobylisy", "pivo": "Pilsner Urquell, Kozel 11°, Volba sládků"},
    {"id": 36, "nazev": "U Korbelu", "ctvrt": "Ládví", "pivo": "Staropramen Smíchov, Staropramen 12°, Ostravar Mustang"},
    {"id": 37, "nazev": "Pivnice U Hrušky", "ctvrt": "Kobylisy", "pivo": "Kácov Hubertus 11°, Únětice 12°"},
    {"id": 38, "nazev": "Hospoda Březiněveská", "ctvrt": "Kobylisy", "pivo": "Bernard 11° Světlý, Bernard Jantar"},
    {"id": 39, "nazev": "Krakora Bar", "ctvrt": "Kobylisy", "pivo": "Chotěboř 11°, Polička Otakar 11°"},
    {"id": 40, "nazev": "Sídlištní Oáza", "ctvrt": "Ládví", "pivo": "Staropramen 10°, Staropramen Nealko"},
    {"id": 143, "nazev": "U Vzdáleného sudu", "ctvrt": "Ládví", "pivo": "Gambrinus 12°, Kozel Tmavý"},
    {"id": 111, "nazev": "Pivnice Střížkov", "ctvrt": "Střížkov", "pivo": "Pilsner Urquell, Radegast 12°"},
    {"id": 112, "nazev": "Hospoda Pod Stříškou", "ctvrt": "Střížkov", "pivo": "Svijany 11°, Kozel 11°"},
    {"id": 113, "nazev": "Restaurace U Medvěda", "ctvrt": "Střížkov", "pivo": "Staropramen 11°, Braník"},
    {"id": 114, "nazev": "Pivnice Bella", "ctvrt": "Střížkov", "pivo": "Bernard 12° Kvasnicový, Bernard Černý"},
    {"id": 115, "nazev": "Sídlištní Krčma", "ctvrt": "Střížkov", "pivo": "Gambrinus 10°, Radegast 10"},
    {"id": 116, "nazev": "Sport Bar Střížkov", "ctvrt": "Střížkov", "pivo": "Kozel 11°, Pilsner Urquell"},
    {"id": 117, "nazev": "Bar Albert", "ctvrt": "Střížkov", "pivo": "Staropramen 12°, Nealko Birell"},
    {"id": 118, "nazev": "Pivnice U Káji", "ctvrt": "Střížkov", "pivo": "Poutník 12°, Chotěboř 11°"},
    {"id": 119, "nazev": "Hospůdka Na Růžku", "ctvrt": "Střížkov", "pivo": "Svijanský Máz, Rohozec"},
    {"id": 120, "nazev": "U Křížku Střížkov", "ctvrt": "Střížkov", "pivo": "Kácov 11°, Únětice 12°"},
    {"id": 41, "nazev": "Pivovarský dvůr Letňany", "ctvrt": "Letňany", "pivo": "Letňanský ležák 11°, Tmavý speciál 13°, Medové pivo"},
    {"id": 42, "nazev": "Restaurace Avion", "ctvrt": "Letňany", "pivo": "Pilsner Urquell, Kozel 11° Světlý, Kozel Černý"},
    {"id": 43, "nazev": "Steak & Beer Šnek", "ctvrt": "Letňany", "pivo": "Bernard 11° Světlý, Bernard Černá lavina, Bernard IPA"},
    {"id": 44, "nazev": "Pivnice Na Verandě", "ctvrt": "Letňany", "pivo": "Gambrinus Excelent 11°, Radegast 12°"},
    {"id": 45, "nazev": "Hospoda U Letců", "ctvrt": "Letňany", "pivo": "Staropramen 11°, Braník 11°"},
    {"id": 46, "nazev": "Pivnice Kobra", "ctvrt": "Letňany", "pivo": "Svijanský Máz 11°, Kozel 10°"},
    {"id": 47, "nazev": "Blue Bar & Beer", "ctvrt": "Letňany", "pivo": "Radegast 10, Pilsner Urquell"},
    {"id": 48, "nazev": "Kavárna a hospůdka Avion", "ctvrt": "Letňany", "pivo": "Kozel 11° Tankový, Birell Pomelo"},
    {"id": 49, "nazev": "Restaurace Broadview", "ctvrt": "Letňany", "pivo": "Pilsner Urquell, Volba sládků"},
    {"id": 50, "nazev": "Ztracené pivo", "ctvrt": "Letňany", "pivo": "Staropramen 12°, Černá Barbora"},
    {"id": 51, "nazev": "U Vystřelenýho oka", "ctvrt": "Žižkov", "pivo": "Pilsner Urquell, Kozel 11°, Kozel Černý"},
    {"id": 52, "nazev": "Pivnice U Járy", "ctvrt": "Žižkov", "pivo": "Svijanský Máz 11°, Rohozec 12°, Bakalář Za studena chmelený"},
    {"id": 53, "nazev": "Pivovar Victor", "ctvrt": "Žižkov", "pivo": "Victor Světlý ležák, Victor Tmavý ležák, Victor Speciál"},
    {"id": 54, "nazev": "U Sadu", "ctvrt": "Žižkov", "pivo": "Sádek 11° (vlastní), Pilsner Urquell, Primátor Weizen, Guinness"},
    {"id": 55, "nazev": "Hospoda Nad Viktorkou", "ctvrt": "Žižkov", "pivo": "Gambrinus 11° Nepaster, Radegast 12°"},
    {"id": 56, "nazev": "U Pižlu", "ctvrt": "Žižkov", "pivo": "Únětice 10°, Únětice 12°, Kácov 11°"},
    {"id": 57, "nazev": "Pivnice u Slovanské Lípy", "ctvrt": "Žižkov", "pivo": "Kout na Šumavě 12°, Tambor 11°, Bakalář"},
    {"id": 58, "nazev": "Hospoda Malkovich", "ctvrt": "Žižkov", "pivo": "Zichovec IPA, Matuška 12°, Clock APA"},
    {"id": 59, "nazev": "Planeta Žižkov", "ctvrt": "Žižkov", "pivo": "Staropramen 11°, Stella Artois"},
    {"id": 60, "nazev": "U Bohouše", "ctvrt": "Žižkov", "pivo": "Pilsner Urquell, Kozel Tmavý"},
    {"id": 61, "nazev": "Vinohradský pivovar", "ctvrt": "Vinohrady", "pivo": "Vinohradská 11°, Vinohradská 12°, Jantarová 13°, Liberator IPA"},
    {"id": 62, "nazev": "BeerGeek Bar", "ctvrt": "Vinohrady", "pivo": "Zichovec Sour, Raven IPA, Falkon Stout, Matuška California"},
    {"id": 63, "nazev": "Hostinec U Vodoucha", "ctvrt": "Vinohrady", "pivo": "Poutník 12°, Koutská 10°, Únětice 12, Chotěboř 11"},
    {"id": 64, "nazev": "Dno Pytle", "ctvrt": "Vinohrady", "pivo": "Bavorská piva z malých pivovarů, Francké samosády"},
    {"id": 65, "nazev": "Hrom do police", "ctvrt": "Vinohrady", "pivo": "Polotmavý Polička Otakar 11°, Eliška 13°"},
    {"id": 66, "nazev": "Lokal Korunní", "ctvrt": "Vinohrady", "pivo": "Pilsner Urquell tankový, Kozel Černý"},
    {"id": 67, "nazev": "Pivnice U Kozla", "ctvrt": "Vinohrady", "pivo": "Kozel 11° z tanku, Kozel Mistrův Nepasterovaný"},
    {"id": 68, "nazev": "Restaurace Hajnovka", "ctvrt": "Vinohrady", "pivo": "Pilsner Urquell, Volba sládků"},
    {"id": 69, "nazev": "Pivni Mozaika", "ctvrt": "Vinohrady", "pivo": "Clock APA, Permon Stout, Raven Sour"},
    {"id": 70, "nazev": "U Bulínů", "ctvrt": "Vinohrady", "pivo": "Pilsner Urquell, Kozel 11° Světlý"},
    {"id": 71, "nazev": "Dva kohouti", "ctvrt": "Karlín", "pivo": "Místní ležák 12° z tanku, Hostující pivovary"},
    {"id": 72, "nazev": "Lokál Hamburk", "ctvrt": "Karlín", "pivo": "Pilsner Urquell z tanku, Kozel Černý"},
    {"id": 73, "nazev": "Pivovarský klub Benedict", "ctvrt": "Karlín", "pivo": "Břevnovský Benedikt 12°, Primátor Weizen, Kácov 11°, Bernard"},
    {"id": 74, "nazev": "Pivo Karlín", "ctvrt": "Karlín", "pivo": "Karlínský ležák 11°, Karlínská IPA 14°"},
    {"id": 75, "nazev": "Bad Flash Bar Karlín", "ctvrt": "Karlín", "pivo": "Bad Flash Torpido IPA, Hostující minipivovary"},
    {"id": 76, "nazev": "Diezenhofer pivnice", "ctvrt": "Karlín", "pivo": "Budweiser Budvar, Budvar Cvikr"},
    {"id": 77, "nazev": "Karlínská pivnice", "ctvrt": "Karlín", "pivo": "Staropramen 11°, Smíchov Tank"},
    {"id": 78, "nazev": "The Pub Karlín", "ctvrt": "Karlín", "pivo": "Pilsner Urquell (vlastní pípa na stole)"},
    {"id": 79, "nazev": "U Saní", "ctvrt": "Karlín", "pivo": "Svijanský Máz 11°, Rohozec 12°"},
    {"id": 80, "nazev": "Peter's Pub", "ctvrt": "Karlín", "pivo": "Pilsner Urquell, Ostravar Mustang"},
    {"id": 81, "nazev": "Automat Matuška", "ctvrt": "Dejvice", "pivo": "Matuška Desítka, Matuška Dvanáctka, California IPA, Apollo Galaxy"},
    {"id": 82, "nazev": "Kulaťák", "ctvrt": "Dejvice", "pivo": "Pilsner Urquell z tanku, Kozel Tmavý, Volba sládků"},
    {"id": 83, "nazev": "Budvarka Dejvice", "ctvrt": "Dejvice", "pivo": "Budweiser Budvar Original, Budvar Cvikr, Budvar Tmavý"},
    {"id": 84, "nazev": "Na Slamníku", "ctvrt": "Dejvice", "pivo": "Únětice 10° nefiltrovaná, Únětice 12° filtrovaná"},
    {"id": 85, "nazev": "Pivovar Bubeneč", "ctvrt": "Dejvice", "pivo": "Bubenečská 11° Světlá, Bubenečská 12° APA, Šesták 10°"},
    {"id": 86, "nazev": "U Pětníka", "ctvrt": "Dejvice", "pivo": "Únětice 12°, Pilsner Urquell, Radegast 10°"},
    {"id": 87, "nazev": "U Veverky", "ctvrt": "Dejvice", "pivo": "Pilsner Urquell perfekt hladinka, Kozel Černý"},
    {"id": 88, "nazev": "Dejvická Sokolovna", "ctvrt": "Dejvice", "pivo": "Gambrinus 11° Nepaster, Pilsner Urquell"},
    {"id": 89, "nazev": "Krkonošská hospoda", "ctvrt": "Dejvice", "pivo": "Hendrych 11°, Trautenberk 12°, Krakonoš 12°"},
    {"id": 90, "nazev": "Base Camp Dejvice", "ctvrt": "Dejvice", "pivo": "Zichovec, Falkon, Clock (Pivotéka & bar)"},
    {"id": 91, "nazev": "Na Verandách (Staropramen)", "ctvrt": "Smíchov", "pivo": "Staropramen Smíchov z tanku, Staropramen 12°, Extra Chmelená 12°, Černá Barbora"},
    {"id": 92, "nazev": "Andělský pivovar", "ctvrt": "Smíchov", "pivo": "Andělský ležák 11°, Andělská 12° Nefiltrovaná, Speciál APA"},
    {"id": 93, "nazev": "Kozlovna Lidická", "ctvrt": "Smíchov", "pivo": "Kozel 11° Tankový, Kozel Mistrův ležák, Kozel Černý"},
    {"id": 94, "nazev": "Beer Time Anděl", "ctvrt": "Smíchov", "pivo": "Zichovec Magor, Clock No.1, Albrecht IPA, Únětice 12°"},
    {"id": 95, "nazev": "Smíchovský Radegast Pub", "ctvrt": "Smíchov", "pivo": "Radegast Rázná 10, Radegast Ryze Hořká 12, Pilsner Urquell"},
    {"id": 96, "nazev": "Hany Bany Smíchov", "ctvrt": "Smíchov", "pivo": "Staropramen 11°, Braník 11°"},
    {"id": 97, "nazev": "Pivnice Jamajka", "ctvrt": "Smíchov", "pivo": "Svijanský Máz 11°, Kozel 10°"},
    {"id": 98, "nazev": "U Perónu", "ctvrt": "Smíchov", "pivo": "Pilsner Urquell, Kozel Černý"},
    {"id": 99, "nazev": "Restaurace Tradice", "ctvrt": "Smíchov", "pivo": "Pilsner Urquell z tanku, Volba sládků"},
    {"id": 100, "nazev": "Pivnice Trilobit", "ctvrt": "Smíchov", "pivo": "Trilobit 11° Světlý, Trilobit Černá liška 13°"},
    {"id": 101, "nazev": "Zlý časy", "ctvrt": "Nusle", "pivo": "Kout na Šumavě, Matuška, Clock, Permon, Albrecht (24 píp z minipivovarů)"},
    {"id": 102, "nazev": "Pivovar Bašta (U Bansethů)", "ctvrt": "Nusle", "pivo": "Bašta 12° Světlá nefiltrovaná, Bašta Polotmavá 12°, Medový speciál"},
    {"id": 103, "nazev": "U pěniček", "ctvrt": "Nusle", "pivo": "Bernard 11°, Bernard 12° Kvasnicový, Bernard Jantar"},
    {"id": 104, "nazev": "Kozlovna Tylor", "ctvrt": "Nusle", "pivo": "Kozel 11° Tankový, Kozel Černý, Pilsner Urquell"},
    {"id": 105, "nazev": "Nuselská pivnice", "ctvrt": "Nusle", "pivo": "Staropramen 11°, Braník 11°"},
    {"id": 106, "nazev": "Sokolovna Nusle", "ctvrt": "Nusle", "pivo": "Gambrinus 11° Nepaster, Pilsner Urquell"},
    {"id": 107, "nazev": "Na Paloučku", "ctvrt": "Nusle", "pivo": "Pilsner Urquell z tanku, Kozel Tmavý"},
    {"id": 108, "nazev": "Pivnice Lidová", "ctvrt": "Nusle", "pivo": "Svijanský Máz 11°, Rohozec 12°"},
    {"id": 109, "nazev": "Hospůdka Omladinářů", "ctvrt": "Nusle", "pivo": "Kácov Hubertus 11°, Bernard 11°"},
    {"id": 110, "nazev": "Pivovar Spojovna", "ctvrt": "Nusle", "pivo": "Spojovací 11° Ležák, Šubrt 12° Tmavý, IPA 14° Študák"},
    {"id": 121, "nazev": "Pivovar Marina", "ctvrt": "Holešovice", "pivo": "Holešovický ležák 12°, Přístavní desítka, Marina IPA"},
    {"id": 122, "nazev": "Pivovar Lajka", "ctvrt": "Holešovice", "pivo": "Lajka 11° Světlá, Sputnik 13° Dark, Craft speciály"},
    {"id": 123, "nazev": "Kozlovna Holešovice", "ctvrt": "Holešovice", "pivo": "Kozel 11° z tanku, Kozel Černý, Pilsner Urquell"},
    {"id": 124, "nazev": "Lokál Nad Stromovkou", "ctvrt": "Holešovice", "pivo": "Pilsner Urquell z tanku, Kozel Tmavý"},
    {"id": 125, "nazev": "Sedmý schod", "ctvrt": "Holešovice", "pivo": "Únětice 10°, Únětice 12°, Bernard Černý"},
    {"id": 126, "nazev": "Holešovická Pivnice", "ctvrt": "Holešovice", "pivo": "Svijany 11°, Gambrinus 11°"},
    {"id": 127, "nazev": "U Průhonu", "ctvrt": "Holešovice", "pivo": "Kácov Hubertus 11°, Staropramen 12°"},
    {"id": 128, "nazev": "U Topolů", "ctvrt": "Holešovice", "pivo": "Radegast 12°, Pilsner Urquell"},
    {"id": 129, "nazev": "Pivotéka BaseCamp", "ctvrt": "Holešovice", "pivo": "Zichovec, Raven, Clock, Matuška"},
    {"id": 130, "nazev": "Hospoda Pod Výtopnou", "ctvrt": "Holešovice", "pivo": "Bernard 11°, Kozel Tmavý"},
    {"id": 131, "nazev": "Břevnovský klášterní pivovar", "ctvrt": "Břevnov", "pivo": "Benedikt 11° Světlý, Benedikt 12° Tmavý, Klášterní IPA"},
    {"id": 132, "nazev": "U Černého lva", "ctvrt": "Břevnov", "pivo": "Pilsner Urquell, Kozel 11°"},
    {"id": 133, "nazev": "Hospoda Konec světa", "ctvrt": "Břevnov", "pivo": "Svijanský Máz, Bernard 11°"},
    {"id": 134, "nazev": "Pivnice Břevnov", "ctvrt": "Břevnov", "pivo": "Staropramen 11°, Braník Jedenáctka"},
    {"id": 135, "nazev": "U Prezidentů", "ctvrt": "Břevnov", "pivo": "Gambrinus 11° Nepaster, Pilsner Urquell"},
    {"id": 136, "nazev": "Na Závisti", "ctvrt": "Břevnov", "pivo": "Kozel Tmavý, Radegast 12°"},
    {"id": 137, "nazev": "Klášterní Šenk", "ctvrt": "Břevnov", "pivo": "Benedikt Světlý ležák, Volba sládků"},
    {"id": 138, "nazev": "Pivnice Dráha", "ctvrt": "Břevnov", "pivo": "Kácov 11°, Únětice 12°"},
    {"id": 139, "nazev": "U Kaštanu", "ctvrt": "Břevnov", "pivo": "Pilsner Urquell, Radegast 10"},
    {"id": 140, "nazev": "Pod Marjánkou", "ctvrt": "Břevnov", "pivo": "Budvar 12°, Chotěboř 11°"},
]


# Major beer brands to expose as filter chips
KNOWN_BRANDS = [
    "Pilsner Urquell", "Kozel", "Gambrinus", "Staropramen", "Radegast",
    "Budvar", "Bernard", "Svijany", "Svijanský Máz", "Únětice", "Kácov",
    "Chotěboř", "Matuška", "Clock", "Zichovec", "Raven", "Permon", "Albrecht",
    "Primátor", "Rohozec", "Poutník", "Bakalář", "Birell", "IPA",
    "Tmavý", "Tmavá", "Pšeničné", "Polotmavý", "Speciál", "Nealko",
    "Bad Flash", "Benedikt", "Falkon", "Kout na Šumavě", "Tambor",
    "Hendrych", "Trautenberk", "Krakonoš", "Stella Artois", "Guinness",
    "Ostravar", "Braník", "Polička", "Flekovský",
]


def extract_beer_tags(pivo: str) -> list[str]:
    """Return the list of known brand tags present in a pivo description."""
    found = []
    lower = pivo.lower()
    for brand in KNOWN_BRANDS:
        if brand.lower() in lower:
            found.append(brand)
    return found
